# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/oktet/CPP/cpp-course/helloasm

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/oktet/CPP/cpp-course/helloasm

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/oktet/CPP/cpp-course/helloasm/CMakeFiles /home/oktet/CPP/cpp-course/helloasm/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/oktet/CPP/cpp-course/helloasm/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named multiply

# Build rule for target.
multiply: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 multiply
.PHONY : multiply

# fast build rule for target.
multiply/fast:
	$(MAKE) -f CMakeFiles/multiply.dir/build.make CMakeFiles/multiply.dir/build
.PHONY : multiply/fast

#=============================================================================
# Target rules for targets named add

# Build rule for target.
add: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 add
.PHONY : add

# fast build rule for target.
add/fast:
	$(MAKE) -f CMakeFiles/add.dir/build.make CMakeFiles/add.dir/build
.PHONY : add/fast

#=============================================================================
# Target rules for targets named echo

# Build rule for target.
echo: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 echo
.PHONY : echo

# fast build rule for target.
echo/fast:
	$(MAKE) -f CMakeFiles/echo.dir/build.make CMakeFiles/echo.dir/build
.PHONY : echo/fast

#=============================================================================
# Target rules for targets named print_rax

# Build rule for target.
print_rax: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 print_rax
.PHONY : print_rax

# fast build rule for target.
print_rax/fast:
	$(MAKE) -f CMakeFiles/print_rax.dir/build.make CMakeFiles/print_rax.dir/build
.PHONY : print_rax/fast

#=============================================================================
# Target rules for targets named count_words

# Build rule for target.
count_words: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 count_words
.PHONY : count_words

# fast build rule for target.
count_words/fast:
	$(MAKE) -f CMakeFiles/count_words.dir/build.make CMakeFiles/count_words.dir/build
.PHONY : count_words/fast

#=============================================================================
# Target rules for targets named count_lines

# Build rule for target.
count_lines: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 count_lines
.PHONY : count_lines

# fast build rule for target.
count_lines/fast:
	$(MAKE) -f CMakeFiles/count_lines.dir/build.make CMakeFiles/count_lines.dir/build
.PHONY : count_lines/fast

#=============================================================================
# Target rules for targets named subtract

# Build rule for target.
subtract: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 subtract
.PHONY : subtract

# fast build rule for target.
subtract/fast:
	$(MAKE) -f CMakeFiles/subtract.dir/build.make CMakeFiles/subtract.dir/build
.PHONY : subtract/fast

add.o: add.asm.o

.PHONY : add.o

# target to build an object file
add.asm.o:
	$(MAKE) -f CMakeFiles/add.dir/build.make CMakeFiles/add.dir/add.asm.o
.PHONY : add.asm.o

count_lines.o: count_lines.asm.o

.PHONY : count_lines.o

# target to build an object file
count_lines.asm.o:
	$(MAKE) -f CMakeFiles/count_lines.dir/build.make CMakeFiles/count_lines.dir/count_lines.asm.o
.PHONY : count_lines.asm.o

count_words.o: count_words.asm.o

.PHONY : count_words.o

# target to build an object file
count_words.asm.o:
	$(MAKE) -f CMakeFiles/count_words.dir/build.make CMakeFiles/count_words.dir/count_words.asm.o
.PHONY : count_words.asm.o

echo.o: echo.asm.o

.PHONY : echo.o

# target to build an object file
echo.asm.o:
	$(MAKE) -f CMakeFiles/echo.dir/build.make CMakeFiles/echo.dir/echo.asm.o
.PHONY : echo.asm.o

multiply.o: multiply.asm.o

.PHONY : multiply.o

# target to build an object file
multiply.asm.o:
	$(MAKE) -f CMakeFiles/multiply.dir/build.make CMakeFiles/multiply.dir/multiply.asm.o
.PHONY : multiply.asm.o

print_rax.o: print_rax.asm.o

.PHONY : print_rax.o

# target to build an object file
print_rax.asm.o:
	$(MAKE) -f CMakeFiles/print_rax.dir/build.make CMakeFiles/print_rax.dir/print_rax.asm.o
.PHONY : print_rax.asm.o

subtract.o: subtract.asm.o

.PHONY : subtract.o

# target to build an object file
subtract.asm.o:
	$(MAKE) -f CMakeFiles/subtract.dir/build.make CMakeFiles/subtract.dir/subtract.asm.o
.PHONY : subtract.asm.o

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... multiply"
	@echo "... edit_cache"
	@echo "... add"
	@echo "... echo"
	@echo "... print_rax"
	@echo "... count_words"
	@echo "... count_lines"
	@echo "... subtract"
	@echo "... add.o"
	@echo "... count_lines.o"
	@echo "... count_words.o"
	@echo "... echo.o"
	@echo "... multiply.o"
	@echo "... print_rax.o"
	@echo "... subtract.o"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

